### ISSUE TITLE
Possible memory leak due to quota exhaustion

### ISSUE THREAD

**Issue by GarimaSharma** [cloudfoundry-community/stackdriver-tools#105]
Hi,

We are using [Stackdriver nozzle tile 1.0.3](https://network.pivotal.io/products/gcp-stackdriver-nozzle#/releases/5378) with PCF 1.11.6

For our stackdriver nozzle vms, in few minutes the memory utilization increases to 98% and the service crashes/restarts. 

**What we anticipate as problem:**
1. We are exceeding metric descriptor quota for the *service account* used. However it is not clear which quota precisely need to be increased. 
2. Memory should not spike if quota is reached rather the content in memory should be flushed on this error. This is causing intermittent failure of our deployments. 

**What we expect out of this issue:**
1. The [installation docs](http://docs.pivotal.io/partners/gcp-sdn/index.html) of stackdriver-nozzle tile for pcf should mention about which quota to be increased and to what(if possible).
2. If the quota is reached, the memory leak should not happen. 

**Logs:**
1. During the time when memory utilization is increasing:
```
{"timestamp":"1503403764.702794075","source":"stackdriver-nozzle","message":"stackdriver-nozzle.metricsBuffer","log_level":2,"data":{"error":"rpc error: code = 8 desc = Your metric descriptor quota has been exhausted"}}
{"timestamp":"1503403764.708293676","source":"stackdriver-nozzle","message":"stackdriver-nozzle.metricsBuffer","log_level":2,"data":{"error":"rpc error: code = 8 desc = Your metric descriptor quota has been exhausted"}}
```

2. When the service crashes:
```

{"timestamp":"1503566611.790120125","source":"stackdriver-nozzle","message":"stackdriver-nozzle.firehose","log_level":3,"data":{"cleanup":"The metrics buffer was successfully flushed before shutdown","error":"read tcp 10.0.0.51:48572-\u003e130.211.228.210:443: read: connection reset by peer","trace":"goroutine 1 [running]:\ngithub.com/cloudfoundry-community/stackdriver-tools/src/stackdriver-nozzle/vendor/github.com/cloudfoundry/lager.(*logger).Fatal(0xc4201842a0, 0x95f4e4, 0x8, 0xc157e0, 0xc5174fa820, 0xc5176e4648, 0x1, 0x1)\n\t/var/vcap/data/compile/stackdriver-nozzle/go/src/github.com/cloudfoundry-community/stackdriver-tools/src/stackdriver-nozzle/vendor/github.com/cloudfoundry/lager/logger.go:131 +0xc7\nmain.main()\n\t/var/vcap/data/compile/stackdriver-nozzle/go/src/github.com/cloudfoundry-community/stackdriver-tools/src/stackdriver-nozzle/main.go:59 +0x43d\n"}}
{"timestamp":"1503566611.792421341","source":"stackdriver-nozzle","message":"stackdriver-nozzle.heartbeater","log_level":1,"data":{"debug":"Stopping heartbeater"}}
{"timestamp":"1503566619.110969305","source":"stackdriver-nozzle","message":"stackdriver-nozzle.version","log_level":1,"data":{"name":"cf-stackdriver-nozzle","release":"1.0.3","user_agent":"cf-stackdriver-nozzle/1.0.3"}}
{"timestamp":"1503566619.120277643","source":"stackdriver-nozzle","message":"stackdriver-nozzle.arguments","log_level":1,"data":{"APIEndpoint":"https://api.gcp.trackerred.com","BatchCount":10,"BatchDuration":1,"DebugNozzle":false,"Events":"CounterEvent,Error,HttpStartStop,LogMessage,ValueMetric,ContainerMetric","HeartbeatRate":30,"NewlineToken":"","Password":"\u003credacted\u003e","ProjectID":"<project-id>","ResolveAppMetadata":true,"SkipSSL":false,"SubscriptionID":"stackdriver-nozzle","Username":"<username>"}}
{"timestamp":"1503566619.138031244","source":"stackdriver-nozzle","message":"stackdriver-nozzle.heartbeater","log_level":1,"data":{"debug":"Starting heartbeater"}}
{"timestamp":"1503566619.802249670","source":"stackdriver-nozzle","message":"stackdriver-nozzle.heartbeater","log_level":1,"data":{"debug":"Starting heartbeater"}}
```

3. Monit status during the last few minutes before crash:
![screen shot 2017-08-24 at 10 23 03 am](https://user-images.githubusercontent.com/1960880/29662957-f7f412ec-88c0-11e7-90df-327d2a322675.png)

4. Memory utilization for one stackdriver nozzle vm: (Rest of the vms looks similar)
![image](https://user-images.githubusercontent.com/1960880/29663631-f809a532-88c3-11e7-89b3-635601c8b243.png)

5. Service logs: 
```
# tail -f stackdriver-nozzle-ctl.err.log
[2017-08-24 01:48:25+0000] ------------ STARTING stackdriver-nozzle-ctl at Thu Aug 24 01:48:24 UTC 2017 --------------
[2017-08-24 06:16:30+0000] ------------ STARTING stackdriver-nozzle-ctl at Thu Aug 24 06:16:30 UTC 2017 --------------
[2017-08-24 08:03:45+0000] ------------ STARTING stackdriver-nozzle-ctl at Thu Aug 24 08:03:45 UTC 2017 --------------
[2017-08-24 09:23:38+0000] ------------ STARTING stackdriver-nozzle-ctl at Thu Aug 24 09:23:38 UTC 2017 --------------
```

```
# tail -f stackdriver-nozzle-ctl.log
[2017-08-24 08:03:45+0000] ------------ STARTING stackdriver-nozzle-ctl at Thu Aug 24 08:03:45 UTC 2017 --------------
[2017-08-24 08:03:45+0000] Removing stale pidfile...
[2017-08-24 09:23:38+0000] ------------ STARTING stackdriver-nozzle-ctl at Thu Aug 24 09:23:38 UTC 2017 --------------
[2017-08-24 09:23:38+0000] Removing stale pidfile...
```

**Comment by johnsonj** [comment]
I attempted to repro this issue on `develop` with the following patch and the issue doesn't repro.

```diff
diff --git a/src/stackdriver-nozzle/stackdriver/metric_client.go b/src/stackdriver-nozzle/stackdriver/metric_client.go
index 25e927a..422a039 100644
--- a/src/stackdriver-nozzle/stackdriver/metric_client.go
+++ b/src/stackdriver-nozzle/stackdriver/metric_client.go
@@ -18,6 +18,7 @@ package stackdriver
 
 import (
 	"context"
+	"errors"
 
 	"cloud.google.com/go/monitoring/apiv3"
 	"github.com/cloudfoundry-community/stackdriver-tools/src/stackdriver-nozzle/version"
@@ -56,8 +57,7 @@ func (m *metricClient) Post(request *monitoringpb.CreateTimeSeriesRequest) error
 }
 
 func (m *metricClient) CreateMetricDescriptor(request *monitoringpb.CreateMetricDescriptorRequest) error {
-	_, err := m.sdMetricClient.CreateMetricDescriptor(m.ctx, request)
-	return err
+	return errors.New("hey now")
 }
 
 func (m *metricClient) ListMetricDescriptors(request *monitoringpb.ListMetricDescriptorsRequest) ([]*metricpb.MetricDescriptor, error) {
@@ -76,6 +76,6 @@ func (m *metricClient) ListMetricDescriptors(request *monitoringpb.ListMetricDes
 		descriptors = append(descriptors, metricDescriptor)
 	}
 
-	return descriptors, nil
+	return []*metricpb.MetricDescriptor{}, nil
 
 }
```

I believe this is due to some bigger changes that have been made in the nozzle pipeline. Please re-open this issue if you see it again.
