### ISSUE TITLE
Shipping multiline stack traces from google-fluentd job for use with Stackdriver Error Reporting

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/stackdriver-tools#64]
I'd like to make use of the Stackdriver Error reporting functionality - https://cloud.google.com/error-reporting/docs/viewing - to track errors that CF platform components are logging.

As a concrete example; the CF UAA component logs verbose multiline Java stacktrace errors to `/var/vcap/sys/log/uaa/uaa.log`

For example:

```
[2016-12-20 18:50:08.070] uaa - 10605 [localhost-startStop-1] .... FATAL --- RecognizeFailureDispatcherServlet: Unable to start UAA application.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor#0' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Cannot resolve reference to bean 'identityZoneResolvingFilter' while setting bean property 'additionalFilters' with key [TypedStringValue: value [#{T(org.cloudfoundry.identity.uaa.security.web.SecurityFilterChainPostProcessor.FilterPosition).position(2)}], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityZoneResolvingFilter' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Cannot resolve reference to bean 'identityZoneProvisioning' while setting bean property 'identityZoneProvisioning'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityZoneProvisioning' defined in ServletContext resource [/WEB-INF/spring/multitenant-endpoints.xml]: Cannot resolve reference to bean 'jdbcTemplate' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [spring/data-source.xml]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedMap(BeanDefinitionValueResolver.java:407)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:165)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        ...snip...
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.cloudfoundry.identity.uaa.web.RecognizeFailureDispatcherServlet.init(RecognizeFailureDispatcherServlet.java:56)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1227)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1140)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1027)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5038)
...snip...
```

My understanding of [StackDriver Error reporting](https://cloud.google.com/error-reporting/docs/formatting-error-messages) is that if we can capture all the stacktrace information in a single log message; then we "automagically" get a host of Stackdriver Error reporting goodness.

My concrete question is around how to ship multiline Java stacktrace log messages; but its part of a more generic question around where logic for understanding the log format should live.

One place I can see the logic going is in the  [`jobs/google-fluentd/templates/vcap.conf`](https://github.com/cloudfoundry-community/stackdriver-tools/blob/master/jobs/google-fluentd/templates/vcap.conf) config.  This could potentially be extended with some more detailed in_tail config format for specific log files - in the case of the of the uaa.log file some custom [`multiline`](http://docs.fluentd.org/articles/in_tail#multiline) config that recognises Java stack traces.

However, before submitting a PR for the above; I'd like to find out if there is a better place to put such logic.

Thanks!

**Comment by johnsonj** [comment]
Hey David,

There's one more piece that needs to happen to make the magic-magic. That's recently been solved by this project (fluent-plugin-detect-exceptions)[https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions]. As you said we need the exception on a single line, this plugin takes care of parsing that.

I need to check to see if that's been merged into a released version of google-fluentd. If it is, I can update our copy of it and perhaps we 'get it for free™' then.

**Comment by mrdavidlaing** [comment]
@johnsonj Sweet - thats a much better approach.

Could you close this issue with a note about the new version numbers once that upstream change has been merged in; and I'll test it out!

**Comment by johnsonj** [comment]
I've got an updated version with the exception detection in [this branch](https://github.com/cloudfoundry-community/stackdriver-tools/tree/pr-add-exception-detection-plugin). Will merge and close once it's verified on my end.

**Comment by johnsonj** [comment]
Should be fixed in: https://storage.googleapis.com/bosh-gcp/beta/stackdriver-tools/stackdriver-tools-0.0.182.tgz

**Comment by johnsonj** [comment]
We need to update fluentd configs, [example](https://github.com/thomasschickinger/kubernetes/pull/1/files)

**Comment by johnsonj** [comment]
@mrdavidlaing give this one a try: https://storage.googleapis.com/bosh-gcp/beta/stackdriver-tools/stackdriver-tools-0.0.184.tgz
